### ISSUE TITLE
[BUG] No component to delete

### ISSUE THREAD

**Issue by oijkn** [PhilSwiss/nexus-cleanup#3]
I configured the variables as below but no image was deleted.
```groovy
// Configuration
def repositoryName = 'docker-internal' // Name of your nexus-repository
def maxArtifactCount = 10              // Max. amount of artifacts to keep in repository
def retentionDays = 0                  // Delete surplus artifacts only when older than X (0 = disable)
```

Here is an example of the log when I run the script : 
```sh
[...]
==================================================
Processing Component: null, <group>/<image>
Found Versions: []
Sorted Versions: []
Remove Versions: []
Component Total Count: 0
Component Remove Count: 0
==================================================
[...]
==================================================
 *** Total Deleted Component Count: 0 ***
 ==================================================
```

Can you help me please ?

Also, it's possible to add a filter to exclude `component.version()` that are in a list ?

```groovy
def excludeArtifactTag = ["stable", "latest"]      // Artifacts name to exclude from delete
```

For the moment I hardly coded it : 

```groovy
def componentVersions = tx.findComponents(Query.builder().where('name = ').param(uniqueComponent.name()).and('version != "latest"').and('version != "stable"').suffix(' ORDER BY last_updated DESC').build(), [repo])
```

**Comment by PhilSwiss** [comment]
As seen in your log, the repository in question is probably of the type **Docker**.

Unfortunately, this script was originally written and tested for **Maven2** repositories only. 
Since **Docker** repositories in Nexus are differently organised than **Maven2** repositories, this will be the reason for the problem.

I will try to clarify this in the documentation, as this information has been missing so far, I apologise for this.

At the moment, it is not possible for me to develop the script in a more advanced way, sorry.
Therefore, I can currently only refer to the existing cleanup possibilities provided by [Nexus](https://help.sonatype.com/repomanager3/nexus-repository-administration/repository-management/cleanup-policies) for Docker repositories.

I will gladly add your suggestion for the "exclude"-filter to the list for future ideas.

**Comment by PhilSwiss** [comment]
- the documentation was clarified to maven2-usage only
- the script will log a warning, if the repository is of the wrong type
